name: run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'

      - name: initialise client
        run: cd client && npm ci

      - name: run test script
        run: npm run test
